server:
  port:
    9090
spring:
  security:
    oauth2:
      client:
        registration:
          burger-admin-client: 
            provider: burger-cloud
            client-id: burger-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9090/login/oauth2/code/{registrationId}"
            scope: writeIngredients, deleteIngredients, openId